name: tests

on:
  push:
    branches:
      - '**'
    tags:
      - '!**'
  pull_request:
    branches:
      - '**'

jobs:
  tests:
    runs-on: ubuntu-18.04
    services:
      # How to use MySQL
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    
    name: Python ${{ matrix.python-version }} for ES ${{ matrix.elasticsearch-version }}
    strategy:
      matrix:
        python-version: [3.7, 3.8]
        elasticsearch-version: [6.8.6]
    
    steps:
    - name: Checkout
      uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # 3.1.0
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@13ae5bb136fac2878aff31522b9efb785519f984 # v4.3.0
      with:
        python-version: ${{ matrix.python-version }}
      
    - name: Configure sysctl limits
      run: |
        sudo swapoff -a
        sudo sysctl -w vm.swappiness=1
        sudo sysctl -w fs.file-max=262144
        sudo sysctl -w vm.max_map_count=262144
      
    - name: Runs Elasticsearch ${{ matrix.elasticsearch-version }}
      uses: elastic/elastic-github-actions/elasticsearch@master
      with:
        stack-version: ${{ matrix.elasticsearch-version }}

    - name: Install and set up Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "PATH=$HOME/.poetry/bin:$PATH" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        poetry install --without grimoirelab -vvv
        poetry add -D coveralls
        poetry run pip install -r requirements_dev.txt

    - name: Verify MySQL connection
      run: |
        sudo apt-get install -y mysql-client libmysqlclient-dev
        mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports[3306] }} -uroot -proot -e "SHOW GRANTS FOR 'root'@'localhost'"
        mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports[3306] }} -uroot -proot mysql
      
    - name: Verify Elasticsearch connection
      run: |
        curl -fsSL "http://localhost:9200/_cat/health?h=status"
      
    - name: Lint with flake8
      run: |
        poetry run flake8

    - name: Tests and Coverage
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd tests
        poetry run coverage run --source=sirmordred run_tests.py
        poetry run coveralls --service=github
